### ISSUE TITLE
Template all atom mask was all zeros error

### ISSUE THREAD

**Issue by double-vin** [hpcaitech/FastFold#144]
I also encountered this problem. [https://github.com/hpcaitech/FastFold/issues/106](url)

I get the following error message:
`
running in multimer mode...
Traceback (most recent call last):
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/templates.py", line 859, in _process_single_hit
    features, realign_warning = _extract_template_features(
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/templates.py", line 651, in _extract_template_features
    raise TemplateAtomMaskAllZerosError(
fastfold.data.templates.TemplateAtomMaskAllZerosError: Template all atom mask was all zeros: 6qx9_A1. Residue range: 49-100

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 546, in <module>
    main(args)
  File "inference.py", line 165, in main
    inference_multimer_model(args)
  File "inference.py", line 280, in inference_multimer_model
    feature_dict = data_processor.process_fasta(
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/data_pipeline.py", line 1165, in process_fasta
    chain_features = self._process_single_chain(
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/data_pipeline.py", line 1114, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process_fasta(
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/data_pipeline.py", line 942, in process_fasta
    template_features = make_template_features(
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/data_pipeline.py", line 76, in make_template_features
    templates_result = template_featurizer.get_templates(
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/templates.py", line 1167, in get_templates
    result = _process_single_hit(
  File "/public/home/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/fastfold/data/templates.py", line 888, in _process_single_hit
    "%s_%s (sum_probs: %.2f, rank: %d): feature extracting errors: "
TypeError: must be real number, not NoneType
`

this here is the input file:
[input.txt](https://github.com/hpcaitech/FastFold/files/10566947/input.txt)

In the fastfold/data/templates.py file，I modified the 884th line **warning=None** to solve this problem.

**Comment by Gy-Lu** [comment]
Hi, could you share your fasta file? I'll try to reproduce it,
In my experience, the main reason of this problem is the illegal sequence in the fasta file.

**Comment by double-vin** [comment]
here is the input file:
[input.zip](https://github.com/hpcaitech/FastFold/files/10751132/input.zip)

**Comment by double-vin** [comment]
This input file works normally on alphafold2. What's the problem？I look forward to your reply.

**Comment by Gy-Lu** [comment]
Hi, sorry for being so late.
I have reproduced the error, and I am solving it. This error would be fixed this weekend.

**Comment by Gy-Lu** [comment]
Hi, this bug has been fixed.
If it is not able to solve your problem, you can reopen this issue.

**Comment by double-vin** [comment]
Thank you! My problem is solved.
