### ISSUE TITLE
submit unsuccessfully

### ISSUE THREAD

**Issue by MrGao1997** [hpcaitech/FastFold#172]
when I submit the task an error occurred, how can I fix it?

Traceback (most recent call last):
  File "/Share/app/FastFold/inference.py", line 36, in <module>
    from fastfold.model.fastnn import set_chunk_size
  File "/Share/app/FastFold/fastfold/model/fastnn/__init__.py", line 1, in <module>
    from .msa import MSACore, ExtraMSACore, ExtraMSABlock, ExtraMSAStack
  File "/Share/app/FastFold/fastfold/model/fastnn/msa.py", line 23, in <module>
    from fastfold.model.fastnn.kernel import LayerNorm, bias_dropout_add
  File "/Share/app/FastFold/fastfold/model/fastnn/kernel/__init__.py", line 2, in <module>
    from .layer_norm import FusedLayerNorm as LayerNorm
  File "/Share/app/FastFold/fastfold/model/fastnn/kernel/layer_norm.py", line 2, in <module>
    from .cuda_native.layer_norm import FusedLayerNormAffineFunction
  File "/Share/app/FastFold/fastfold/model/fastnn/kernel/cuda_native/layer_norm.py", line 5, in <module>
    fastfold_layer_norm_cuda = importlib.import_module("fastfold_layer_norm_cuda")
  File "/Share/app/miniconda3.9-pytorch/envs/fastfold/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'fastfold_layer_norm_cuda'

**Comment by Gy-Lu** [comment]
Hi, have you installed FastFold before using?

**Comment by MrGao1997** [comment]
I have installed it but maybe some package was not suitable, so it was always failure when I sbatch job.

However, what confused me is I do not kown where the wrong is. And can you help me?

Thanks a lot.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/03/2023 14:22 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [hpcaitech/FastFold] submit unsuccessfully (Issue #172) |

Hi, have you installed FastFold before using?

**Comment by Gy-Lu** [comment]
Hi, sorry for being late.
I am not sure about the environment you run the code and the one you install FastFold is the same one.
The error message indicates there is no CUDA kernel module that should be compiled when installing FastFold.

**Comment by awer-A** [comment]
@MrGao1997 I encountered the same issue, have you solved it now? Can you tell me?
