### ISSUE TITLE
CUDA error (Illegal memory access)

### ISSUE THREAD

**Issue by gahdritz** [hpcaitech/FastFold#19]
I installed FastFold from a fresh clone according to the instructions in the README and ran the following:

```
import torch
from fastfold.model.fastnn.kernel import softmax


seq = 2500
h, n, c = 8, 384, 2
dtype = torch.float32
q = torch.rand([seq, h, n, c], device="cuda:0", dtype=dtype, requires_grad=True)
k = torch.rand([seq, h, n, c], device="cuda:0", dtype=dtype, requires_grad=True)
s = softmax(torch.matmul(q, k.transpose(-1, -2)))
print(s)
```
on an A100 using CUDA version 11.4. This consistently generates the following error:

```
Traceback (most recent call last):
  File "test_softmax.py", line 11, in <module>
    print(s)
  File "/mnt/home/dberenberg/gustaf_stuff/experiments/softmax/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/torch/_tensor.py", line 305, in __repr__
    return torch._tensor_str._str(self)
  File "/mnt/home/dberenberg/gustaf_stuff/experiments/softmax/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/torch/_tensor_str.py", line 434, in _str
    return _str_intern(self)
  File "/mnt/home/dberenberg/gustaf_stuff/experiments/softmax/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/torch/_tensor_str.py", line 409, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/mnt/home/dberenberg/gustaf_stuff/experiments/softmax/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/torch/_tensor_str.py", line 264, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/mnt/home/dberenberg/gustaf_stuff/experiments/softmax/FastFold/lib/conda/envs/fastfold/lib/python3.8/site-packages/torch/_tensor_str.py", line 100, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
It can be made to work by decreasing `seq`. For my particular setup, the threshold seems to be around 2000. Setting `CUDA_LAUNCH_BLOCKING` doesn't seem to do anything. Any tips for getting this working for tensors as large as [5120, 8, 384, 384], which appear in the AlphaFold pipeline?

**Comment by Shenggan** [comment]
I think this bug is because, in the case that the input size of `softmax` is too large, it may overflow when calculating `rows`, I submitted a PR #20  , you can try to see if it fixes this problem.

**Comment by gahdritz** [comment]
Ah yes---you're totally right. I've been writing Python for far too long...

**Comment by Shenggan** [comment]
OK, PR merged. Thanks for reporting this bug.
